Name	Image	Metal	Mineral	Energy	Worker	Turns	Requirements	Score
Fighter	https://beta.darkgalaxy.com/images/units/small/fighter.gif	[!Fighter:CONDITION:Metal!]	[!Fighter:CONDITION:Mineral!]	[!Fighter:CONDITION:Energy!]	[!Fighter:CONDITION:Worker!]	[!Fighter:CREATE:Turns!]	[!Fighter:REQUIREMENTS:0!]	[!Fighter:SCORE:Asset!]
Bomber	https://beta.darkgalaxy.com/images/units/small/bomber.gif	[!Bomber:CONDITION:Metal!]	[!Bomber:CONDITION:Mineral!]	[!Bomber:CONDITION:Energy!]	[!Bomber:CONDITION:Worker!]	[!Bomber:CREATE:Turns!]	[!Bomber:REQUIREMENTS:0!]	[!Bomber:SCORE:Asset!]
Frigate	https://beta.darkgalaxy.com/images/units/small/frigate.gif	[!Frigate:CONDITION:Metal!]	[!Frigate:CONDITION:Mineral!]	[!Frigate:CONDITION:Energy!]	[!Frigate:CONDITION:Worker!]	[!Frigate:CREATE:Turns!]	[!Frigate:REQUIREMENTS:0!]	[!Frigate:SCORE:Asset!]
Destroyer	https://beta.darkgalaxy.com/images/units/small/destroyer.gif	[!Destroyer:CONDITION:Metal!]	[!Destroyer:CONDITION:Mineral!]	[!Destroyer:CONDITION:Energy!]	[!Destroyer:CONDITION:Worker!]	[!Destroyer:CREATE:Turns!]	[!Destroyer:REQUIREMENTS:0!]	[!Destroyer:SCORE:Asset!]
Cruiser	https://beta.darkgalaxy.com/images/units/small/cruiser.gif	[!Cruiser:CONDITION:Metal!]	[!Cruiser:CONDITION:Mineral!]	[!Cruiser:CONDITION:Energy!]	[!Cruiser:CONDITION:Worker!]	[!Cruiser:CREATE:Turns!]	[!Cruiser:REQUIREMENTS:0!]	[!Cruiser:SCORE:Asset!]
Battleship https://beta.darkgalaxy.com/images/units/small/battleship.gif	[!Battleship:CONDITION:Metal!]	[!Battleship:CONDITION:Mineral!]	[!Battleship:CONDITION:Energy!]	[!Battleship:CONDITION:Worker!]	[!Battleship:CREATE:Turns!]	[!Battleship:REQUIREMENTS:0!]	[!Battleship:SCORE:Asset!]
Outpost Ship	https://beta.darkgalaxy.com/images/units/small/outpost_ship.gif	[!Outpost_Ship:CONDITION:Metal!]	[!Outpost_Ship:CONDITION:Mineral!]	[!Outpost_Ship:CONDITION:Energy!]	[!Outpost_Ship:CONDITION:Worker!]	[!Outpost_Ship:CREATE:Turns!]	[!Outpost_Ship:REQUIREMENTS:0!]	[!Outpost_Ship:SCORE:Asset!]
Invasion Ship	https://beta.darkgalaxy.com/images/units/small/invasion_ship.gif	[!Invasion_Ship:CONDITION:Metal!]	[!Invasion_Ship:CONDITION:Mineral!]	[!Invasion_Ship:CONDITION:Energy!]	[!Invasion_Ship:CONDITION:Worker!]	[!Invasion_Ship:CREATE:Turns!]	[!Invasion_Ship:REQUIREMENTS:0!]	[!Invasion_Ship:SCORE:Asset!]
Freighter	https://beta.darkgalaxy.com/images/units/small/freighter.gif	[!Freighter:CONDITION:Metal!]	[!Freighter:CONDITION:Mineral!]	[!Freighter:CONDITION:Energy!]	[!Freighter:CONDITION:Worker!]	[!Freighter:CREATE:Turns!]	[!Freighter:REQUIREMENTS:0!]	[!Freighter:SCORE:Asset!]
Trader	https://beta.darkgalaxy.com/images/units/small/trader.gif	[!Trader:CONDITION:Metal!]	[!Trader:CONDITION:Mineral!]	[!Trader:CONDITION:Energy!]	[!Trader:CONDITION:Worker!]	[!Trader:CREATE:Turns!]	[!Trader:REQUIREMENTS:0!]	[!Trader:SCORE:Asset!]
Holo Projector		[!Holo_Projector:CONDITION:Metal!]	[!Holo_Projector:CONDITION:Mineral!]	[!Holo_Projector:CONDITION:Energy!]	[!Holo_Projector:CONDITION:Worker!]	[!Holo_Projector:CREATE:Turns!]	[!Holo_Projector:REQUIREMENTS:0!]	[!Holo_Projector:SCORE:Asset!]
Holo Fighter		[!Holo_Fighter:CONDITION:Metal!]	[!Holo_Fighter:CONDITION:Mineral!]	[!Holo_Fighter:CONDITION:Energy!]	[!Holo_Fighter:CONDITION:Worker!]	[!Holo_Fighter:CREATE:Turns!]	[!Holo_Fighter:REQUIREMENTS:0!]	[!Holo_Fighter:SCORE:Asset!]
Holo Bomber		[!Holo_Bomber:CONDITION:Metal!]	[!Holo_Bomber:CONDITION:Mineral!]	[!Holo_Bomber:CONDITION:Energy!]	[!Holo_Bomber:CONDITION:Worker!]	[!Holo_Bomber:CREATE:Turns!]	[!Holo_Bomber:REQUIREMENTS:0!]	[!Holo_Bomber:SCORE:Asset!]
Holo Frigate		[!Holo_Frigate:CONDITION:Metal!]	[!Holo_Frigate:CONDITION:Mineral!]	[!Holo_Frigate:CONDITION:Energy!]	[!Holo_Frigate:CONDITION:Worker!]	[!Holo_Frigate:CREATE:Turns!]	[!Holo_Frigate:REQUIREMENTS:0!]	[!Holo_Frigate:SCORE:Asset!]
Holo Destroyer		[!Holo_Destroyer:CONDITION:Metal!]	[!Holo_Destroyer:CONDITION:Mineral!]	[!Holo_Destroyer:CONDITION:Energy!]	[!Holo_Destroyer:CONDITION:Worker!]	[!Holo_Destroyer:CREATE:Turns!]	[!Holo_Destroyer:REQUIREMENTS:0!]	[!Holo_Destroyer:SCORE:Asset!]
Holo Cruiser		[!Holo_Cruiser:CONDITION:Metal!]	[!Holo_Cruiser:CONDITION:Mineral!]	[!Holo_Cruiser:CONDITION:Energy!]	[!Holo_Cruiser:CONDITION:Worker!]	[!Holo_Cruiser:CREATE:Turns!]	[!Holo_Cruiser:REQUIREMENTS:0!]	[!Holo_Cruiser:SCORE:Asset!]
Holo Battleship		[!Holo_Battleship:CONDITION:Metal!]	[!Holo_Battleship:CONDITION:Mineral!]	[!Holo_Battleship:CONDITION:Energy!]	[!Holo_Battleship:CONDITION:Worker!]	[!Holo_Battleship:CREATE:Turns!]	[!Holo_Battleship:REQUIREMENTS:0!]	[!Holo_Battleship:SCORE:Asset!]



